#!/bin/bash

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#BCBAB8'
TEXT='#BCBAB8'
WRONG='#625757'
VERIFYING='#625757'
TEST='ff0008'


#insidever-color -
#ringver-color - 
#insidewrong-color - внутри
#ringwrong-color - цвет окружности 
#inside-color - цвет внутри окружности
#ring-color - полная окружность
#line-color - внутренняя окружность
#separator-color - границы сектора
#verif-color - verifying
#wrong-color - no input/wrong passwd
#time-color - цвет времени
#date-color - цвет даты
#layout-color - цвет раскладки 
#keyhl-color - нажатия 
#bshl-color - отмена нажатий

i3lock -ec 00000000 \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$BLANK   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 5                    \
--clock                      \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"       \
--keylayout 1                \
--indicator                     \
#--battery
